//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTVLibraryTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileTVLibraryTest.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;!--
        ///::::: languages ....................... [ css (ii), javascript (1.+), rss (2.0 -m -e), xhtml (1.0) ]
        ///::::: processing ...................... [ esi, ssi, xslt (1.0) ]
        ///::::: developers ...................... [ clewin ] test
        ///--&gt;
        ///
        ///
        ///&lt;!-- include (SSI) [ esi variables ] --&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///			
        ///			
        ///			
        ///			
        ///		
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        ///	
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DiscoverySchedule {
            get {
                return ResourceManager.GetString("DiscoverySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; lang=&quot;en&quot; xml:lang=&quot;en&quot;&gt;        ///
        ///&lt;head&gt;        ///
        ///	&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;/&gt;        ///
        ///	&lt;title&gt;FX Networks&lt;/title&gt;        ///
        ///	&lt;meta name=&quot;description&quot; content=&quot;Official site. FX Network is the home of award-winning, original television. Shows include Sons of Anarchy, Justified, Terriers, It&apos;s Always Sunny in Philadelphia, Archer,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FXSchedule {
            get {
                return ResourceManager.GetString("FXSchedule", resourceCulture);
            }
        }
    }
}
